/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketbookingsystem;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rinzler
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sgUserText = new javax.swing.JTextField();
        sgPassText = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        sgSignUpBt = new javax.swing.JButton();
        sgResetBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sgLoginBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Fira Mono Medium", 1, 24)); // NOI18N
        jLabel1.setText("Sign Up");

        sgSignUpBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        sgSignUpBt.setText("Sign Up");
        sgSignUpBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgSignUpBtActionPerformed(evt);
            }
        });

        sgResetBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        sgResetBt.setText("Reset");
        sgResetBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgResetBtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        sgLoginBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        sgLoginBt.setText("Login");
        sgLoginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgLoginBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(sgSignUpBt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(sgResetBt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sgPassText)
                            .addComponent(sgUserText))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sgLoginBt)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sgLoginBt)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgPassText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgSignUpBt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgResetBt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sgResetBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgResetBtActionPerformed
        // TODO add your handling code here:
        sgUserText.setText("");
        sgPassText.setText("");
    }//GEN-LAST:event_sgResetBtActionPerformed

    private void sgSignUpBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgSignUpBtActionPerformed
        // TODO add your handling code here:
        if(TicketBookingSystem.globalFlag == 0){
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?useSSL=false", "root", "");

                String username = sgUserText.getText();
                String password = sgPassText.getText();

                Statement stm = con.createStatement();
                String sql = "SELECT * FROM login where lg_username = '"+username+"' and lg_password = '"+password+"'";
                ResultSet rs = stm.executeQuery(sql);

                if(rs.next()){
                    dispose();
                    LoginPage lpage = new LoginPage();
                    lpage.show();
                }
                else if(username.isEmpty() || password.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Fill all fields...");
                    sgUserText.setText("");
                    sgPassText.setText("");
                }
                else{
                    PreparedStatement pstmt = con.prepareStatement("INSERT INTO login (lg_username, lg_password) VALUES(?,?)");
                    pstmt.setString(1, username);
                    pstmt.setString(2, password);
                    pstmt.executeUpdate();
                    TicketBookingSystem.globalUser = username;
                    TicketBookingSystem.globalFlag = 1;
                    dispose();
                    TicketBooking tpage = new TicketBooking();
                    tpage.show();
                }
                con.close();

            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
        else{
            dispose();
            TicketBooking tpage = new TicketBooking();
            tpage.show();
        }
    }//GEN-LAST:event_sgSignUpBtActionPerformed

    private void sgLoginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgLoginBtActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage lpage = new LoginPage();
        lpage.show();
    }//GEN-LAST:event_sgLoginBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton sgLoginBt;
    private javax.swing.JPasswordField sgPassText;
    private javax.swing.JButton sgResetBt;
    private javax.swing.JButton sgSignUpBt;
    private javax.swing.JTextField sgUserText;
    // End of variables declaration//GEN-END:variables
}
