/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketbookingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rinzler
 */
public class TicketBooking extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public TicketBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbTicketsBt = new javax.swing.JButton();
        tbLogoutBt = new javax.swing.JButton();
        tbName = new javax.swing.JTextField();
        tbPhone = new javax.swing.JTextField();
        tbStart = new javax.swing.JTextField();
        tbDestination = new javax.swing.JTextField();
        tbTime = new javax.swing.JTextField();
        tbSeats = new javax.swing.JTextField();
        tbSubmitBt = new javax.swing.JButton();
        tbResetBt = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Fira Mono Medium", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bus Ticket Booking");

        jLabel3.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone No");

        jLabel1.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        jLabel4.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Start");

        jLabel5.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Destination");

        jLabel6.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Time");

        jLabel7.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("No. of Seats");

        tbTicketsBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        tbTicketsBt.setText("Tickets");
        tbTicketsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTicketsBtActionPerformed(evt);
            }
        });

        tbLogoutBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        tbLogoutBt.setText("Logout");
        tbLogoutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLogoutBtActionPerformed(evt);
            }
        });

        tbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNameActionPerformed(evt);
            }
        });

        tbSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSeatsActionPerformed(evt);
            }
        });

        tbSubmitBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        tbSubmitBt.setText("Submit");
        tbSubmitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSubmitBtActionPerformed(evt);
            }
        });

        tbResetBt.setFont(new java.awt.Font("Fira Mono Medium", 1, 14)); // NOI18N
        tbResetBt.setText("Reset");
        tbResetBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbResetBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tbTicketsBt)
                                .addGap(11, 11, 11)
                                .addComponent(tbLogoutBt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tbSubmitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbResetBt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(tbName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbDestination, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2)))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTicketsBt)
                    .addComponent(tbLogoutBt))
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tbSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbResetBt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbSubmitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTicketsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTicketsBtActionPerformed
        // TODO add your handling code here:
        dispose();
        TicketsLog tlpage = new TicketsLog();
        tlpage.show();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?useSSL=false", "root", "");
            
            Statement st = con.createStatement();
            String sql = "SELECT * FROM ticketbooking where tb_username = '"+TicketBookingSystem.globalUser+"'";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String id = String.valueOf(rs.getInt("tb_id"));
                String name = rs.getString("tb_name");
                String phone = rs.getString("tb_phone");
                String start = rs.getString("tb_start");
                String destination = rs.getString("tb_destination");
                String time = rs.getString("tb_time");
                String seats = rs.getString("tb_seats");
                
                //String array for storeing data into jtable
                String tbData[] = {id, name, phone, start, destination, time, seats};
                DefaultTableModel tbModel = (DefaultTableModel)TicketsLog.jTable1.getModel();
                
                tbModel.addRow(tbData);
            }
            
        }catch(Exception e){
                System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_tbTicketsBtActionPerformed

    private void tbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNameActionPerformed

    private void tbSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSeatsActionPerformed

    private void tbSubmitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSubmitBtActionPerformed
        // TODO add your handling code here:
        if(TicketBookingSystem.globalFlag == 1){
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproject?useSSL=false", "root", "");
            
            String name = tbName.getText();
            String phone = tbPhone.getText();
            String start = tbStart.getText();
            String destination = tbDestination.getText();
            String time = tbTime.getText();
            String seats = tbSeats.getText();
            
            //JOptionPane.showMessageDialog(this, phone);
            if(name.isEmpty()|| phone.isEmpty() || start.isEmpty() || destination.isEmpty() || time.isEmpty() || seats.isEmpty()){
                JOptionPane.showMessageDialog(this, "Fill all the fields...");
                tbName.setText("");
                tbPhone.setText("");
                tbStart.setText("");
                tbDestination.setText("");
                tbTime.setText("");
                tbSeats.setText("");
            }
            else
            {
                PreparedStatement pstmt = con.prepareStatement("INSERT INTO ticketbooking (tb_username, tb_name, tb_phone, tb_start, tb_destination, tb_time, tb_seats) VALUES(?,?,?,?,?,?,?)");
                pstmt.setString(1, TicketBookingSystem.globalUser);
                pstmt.setString(2, name);
                pstmt.setString(3, phone);
                pstmt.setString(4, start);
                pstmt.setString(5, destination);
                pstmt.setString(6, time);
                pstmt.setString(7, seats);
                pstmt.executeUpdate();
                dispose();
                JOptionPane.showMessageDialog(this, "Ticket Booked");
                TicketBooking tpage = new TicketBooking();
                tpage.show();
            }
            con.close();
            
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
        else{
            dispose();
            JOptionPane.showMessageDialog(this, "Login First");
            LoginPage lpage = new LoginPage();
            lpage.show();
        }
    }//GEN-LAST:event_tbSubmitBtActionPerformed

    private void tbResetBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbResetBtActionPerformed
        // TODO add your handling code here:
        tbName.setText("");
        tbPhone.setText("");
        tbStart.setText("");
        tbDestination.setText("");
        tbTime.setText("");
        tbSeats.setText("");
    }//GEN-LAST:event_tbResetBtActionPerformed

    private void tbLogoutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLogoutBtActionPerformed
        // TODO add your handling code here:
        TicketBookingSystem.globalFlag = 0;
        TicketBookingSystem.globalUser = "";
        dispose();
        LoginPage lpage = new LoginPage();
        lpage.show();
    }//GEN-LAST:event_tbLogoutBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tbDestination;
    private javax.swing.JButton tbLogoutBt;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbPhone;
    private javax.swing.JButton tbResetBt;
    private javax.swing.JTextField tbSeats;
    private javax.swing.JTextField tbStart;
    private javax.swing.JButton tbSubmitBt;
    private javax.swing.JButton tbTicketsBt;
    private javax.swing.JTextField tbTime;
    // End of variables declaration//GEN-END:variables
}
